name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: 1StrongPwd%
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v4

    - name: Start Mysql server
      run: sudo systemctl start mysql.service

    - name: Start PostgreSql server and create test database
      run: |
        sudo systemctl start postgresql.service
        pg_isready
        sudo -u postgres psql -c "CREATE USER runner WITH SUPERUSER CREATEDB CREATEROLE PASSWORD '1StrongPwd%'"
        sudo -u postgres psql -c "CREATE DATABASE test"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check coding standards
      run: vendor/bin/phpcs --standard=vendor/piko/core/coding-standard src

    - name: Code Analysis
      run: vendor/bin/phpstan

    - name: Run test suite
      env:
        XDEBUG_MODE: coverage
      run: vendor/bin/phpunit --coverage-clover clover.xml

    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer require php-coveralls/php-coveralls -n -W
        vendor/bin/php-coveralls --coverage_clover=clover.xml -v --json_path=coveralls-upload.json
