name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, mysql, mssql, pgsql]

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: 1StrongPwd%
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P '1StrongPwd%' -Q 'SELECT 1' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
    - uses: actions/checkout@v4

    - name: Start Mysql server (only for mysql)
      if: matrix.db == 'mysql'
      run: |
          sudo systemctl start mysql.service
          mysqladmin ping --silent

    - name: Start PostgreSql server and create test database (only for pgsql)
      if: matrix.db == 'pgsql'
      run: |
        sudo systemctl start postgresql.service
        pg_isready
        sudo -u postgres psql -c "CREATE USER runner WITH SUPERUSER CREATEDB CREATEROLE PASSWORD '1StrongPwd%'"
        sudo -u postgres psql -c "CREATE DATABASE test"

    - name: Wait MSSQL (only for mssql)
      if: matrix.db == 'mssql'
      run: |
        for i in {1..30}; do
          if nc -z 127.0.0.1 1433; then
            echo "MSSQL is reachable"
            exit 0
          fi
          sleep 2
        done
        echo "MSSQL did not become ready in time"
        exit 1

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Check coding standards
      run: vendor/bin/phpcs --standard=vendor/piko/core/coding-standard src

    - name: Code Analysis
      run: vendor/bin/phpstan

    - name: Run test suite
      env:
        DB_DRIVER: ${{ matrix.db }}
      run: |
        mkdir -p build/logs
        if [ "${{ matrix.db }}" = "sqlite" ]; then
          XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml
        else
          vendor/bin/phpunit --no-coverage
        fi

    - name: Upload coverage results to Coveralls
      if: matrix.db == 'sqlite'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer require php-coveralls/php-coveralls -n -W
        vendor/bin/php-coveralls --coverage_clover=clover.xml -v --json_path=coveralls-upload.json
